RECIPES.push(
{id:"barbari",s:"LEVANT",c:{en:"Iran",it:"Iran",sv:"Iran"},k:"bread",time:120,
   t:{en:"Nan-e barbari",it:"Nan-e barbari",sv:"Nan-e barbari"},
   w:{en:"Iranian breakfast bread with a flour-and-water glaze and nigella. Tear and dip in honey or feta.",
      it:"Pane della colazione iraniana, glassa di farina e nigella. Con miele o feta.",
      sv:"Iranskt frukostbröd med mjölglasyr och nigella. Doppa i honung eller feta."},
   i:{en:"400 g flour (80 g wholemeal), 7 g instant yeast, 8 g salt, 1 tsp honey, 260 ml warm water, 1 tbsp oil. Glaze: 1 tsp flour + 3 tbsp water cooked 1 minute. Nigella or sesame.",
      it:"400 g farina (80 g integrale), 7 g lievito, 8 g sale, 1 cucchiaino miele, 260 ml acqua, 1 cucchiaio olio. Glass: 1 cucchiaino farina + 3 cucchiai acqua, 1 min. Nigella o sesamo.",
      sv:"400 g mjöl (80 g fullkorn), 7 g jäst, 8 g salt, 1 tsk honung, 260 ml vatten, 1 msk olja. Glasyr: 1 tsk mjöl + 3 msk vatten, 1 min. Nigella eller sesam."},
   p:{en:"Knead, rise 1 hour. Divide in two ovals. Rest 20 minutes. Heat oven to 240 °C. Stretch each oval, press long grooves with your fingers, brush the glaze, seed. Bake 12–15 minutes.",
      it:"1 ora di lievitazione. Due ovali, 20 min. Solchi con le dita, glassa, semi. 240 °C 12–15 minuti.",
      sv:"Jäs 1 tim. Två ovaler, 20 min. Räffla med fingrarna, pensla, fröer. 240 °C 12–15 min."}},

  {id:"basbousa",s:"AFRICA",c:{en:"Egypt",it:"Egitto",sv:"Egypten"},k:"cake",time:50,
   t:{en:"Basbousa",it:"Basbousa",sv:"Basbousa"},
   w:{en:"Semolina and yogurt cake. A light honey-lemon syrup instead of the usual heavy sugar soak.",
      it:"Torta di semola e yogurt. Sciroppo leggero di miele e limone, non la bagna stucchevole.",
      sv:"Semolina och yoghurt. Lätt honungs-citronlag, inte den tunga sockersoppan."},
   i:{en:"200 g fine semolina, 80 g sugar, 1 tsp baking powder, 200 g yogurt, 80 ml olive oil, 1 egg, 1 tsp vanilla, handful of almonds. Syrup: 60 ml water, 40 g honey, juice of ½ lemon.",
      it:"200 g semola, 80 g zucchero, 1 cucchiaino lievito, 200 g yogurt, 80 ml olio, 1 uovo, vaniglia, mandorle. Sciroppo: 60 ml acqua, 40 g miele, mezzo limone.",
      sv:"200 g semolina, 80 g socker, 1 tsk bakpulver, 200 g yoghurt, 80 ml olivolja, 1 ägg, vanilj, mandel. Lag: 60 ml vatten, 40 g honung, ½ citron."},
   p:{en:"Heat oven to 180 °C. Mix batter, spread in a 20 cm tin, score diamonds and set an almond on each. Bake 30–35 minutes. Simmer syrup 3 minutes; pour over the hot cake. Cool before lifting.",
      it:"Forno 180 °C. Spalma, incidi rombi, una mandorla. 30–35 min. Sciroppo sui rombi caldi.",
      sv:"Ugn 180 °C. Smet i form, rita rutor, en mandel. 30–35 min. Lagen över den heta kakan."}},

  {id:"khobz",s:"AFRICA",c:{en:"Morocco",it:"Marocco",sv:"Marocko"},k:"bread",time:130,
   t:{en:"Khobz",it:"Khobz",sv:"Khobz"},
   w:{en:"The round Moroccan loaf that scoops tagine. Semolina on the crust, a little wholemeal inside.",
      it:"La pagnotta tonda con cui si raccoglie il tajine. Semola sulla crosta.",
      sv:"Det runda marockanska brödet till tajine. Semolina på skorpan."},
   i:{en:"350 g flour, 50 g fine semolina plus extra for dusting, 7 g instant yeast, 8 g salt, 1 tsp honey, 260 ml warm water, 1 tbsp olive oil.",
      it:"350 g farina, 50 g semola fine + altra per spolverare, 7 g lievito, 8 g sale, 1 cucchiaino miele, 260 ml acqua, 1 cucchiaio olio.",
      sv:"350 g mjöl, 50 g fin semolina + extra, 7 g jäst, 8 g salt, 1 tsk honung, 260 ml vatten, 1 msk olja."},
   p:{en:"Knead 8 minutes. Rise 1 hour. Shape two discs 2 cm thick. Dust with semolina, rest 30 minutes. Heat oven to 220 °C. Prick the tops. Bake 18–22 minutes until deep gold.",
      it:"8 minuti, 1 ora. Due dischi da 2 cm, semola, 30 min. Pungi. 220 °C 18–22 minuti.",
      sv:"Knåda 8 min, jäs 1 tim. Två diskar 2 cm, semolina, 30 min. Nagga. 220 °C 18–22 min."}},

  {id:"injera",s:"AFRICA",c:{en:"Ethiopia",it:"Etiopia",sv:"Etiopien"},k:"flatbread",time:20,
   t:{en:"Injera (quick)",it:"Injera (veloce)",sv:"Injera (snabb)"},
   w:{en:"Teff is Ethiopia’s grain: mineral-rich, naturally gluten-free. True injera ferments days; this skillet version keeps the sour hint with yogurt.",
      it:"Il teff è il cereale d’Etiopia. L’injera vera fermenta giorni; qui lo yogurt dà l’acido.",
      sv:"Teff är Etiopiens säd. Äkta injera jäser i dagar; här ger yoghurt syran."},
   i:{en:"200 g teff flour (or 120 g teff + 80 g wholemeal), ½ tsp salt, ½ tsp baking soda, 250 ml water, 80 g plain yogurt, oil for the pan.",
      it:"200 g farina di teff (o 120 teff + 80 integrale), ½ cucchiaino sale, ½ cucchiaino bicarbonato, 250 ml acqua, 80 g yogurt, olio per la padella.",
      sv:"200 g teffmjöl (eller 120 teff + 80 fullkorn), ½ tsk salt, ½ tsk bikarbonat, 250 ml vatten, 80 g yoghurt, olja till pannan."},
   p:{en:"Whisk a thin batter. Rest 10 minutes. Heat a large non-stick pan on medium. Pour a ladle, swirl like a crêpe. Cover 2–3 minutes — bubbles should set, do not flip. Stack under a cloth. Serve under stews, not as a wrap.",
      it:"Pastella liquida, 10 min. Padella, un mestolo, copri 2–3 min. Non girare. Sotto allo stufato.",
      sv:"Tunn smet, 10 min. Panna, slev, lock 2–3 min. Vänd inte. Under grytan, inte som wrap."}},

  {id:"himbasha",s:"AFRICA",c:{en:"Eritrea",it:"Eritrea",sv:"Eritrea"},k:"bread",time:120,
   t:{en:"Himbasha",it:"Himbasha",sv:"Himbasha"},
   w:{en:"Festive Eritrean bread, lightly sweet, scored like a wheel, with cardamom and sesame.",
      it:"Pane di festa eritreo, poco dolce, inciso a ruota, cardamomo e sesamo.",
      sv:"Eritreanskt högtidsbröd, lätt sött, ristat som ett hjul, kardemumma och sesam."},
   i:{en:"400 g flour (80 g wholemeal), 7 g instant yeast, ½ tsp salt, 2 tbsp honey, ½ tsp ground cardamom, 240 ml warm water, 2 tbsp olive oil, sesame seeds.",
      it:"400 g farina (80 g integrale), 7 g lievito, ½ cucchiaino sale, 2 cucchiai miele, ½ cucchiaino cardamomo, 240 ml acqua, 2 cucchiai olio, sesamo.",
      sv:"400 g mjöl (80 g fullkorn), 7 g jäst, ½ tsk salt, 2 msk honung, ½ tsk kardemumma, 240 ml vatten, 2 msk olja, sesam."},
   p:{en:"Knead, rise 1 hour. Press into an oiled 26 cm pan. Rise 30 minutes. Brush with oil, sesame, score a wheel with a knife. Bake at 200 °C 20–25 minutes.",
      it:"1 ora. In teglia 26 cm, 30 min. Olio, sesamo, ruota col coltello. 200 °C 20–25 minuti.",
      sv:"Jäs 1 tim. I form 26 cm, 30 min. Olja, sesam, rista ett hjul. 200 °C 20–25 min."}},

  {id:"mealie",s:"AFRICA",c:{en:"South Africa",it:"Sudafrica",sv:"Sydafrika"},k:"bread",time:55,
   t:{en:"Mealie bread",it:"Pane di mais sudafricano",sv:"Mealie-bröd"},
   w:{en:"Sweetcorn baked into a loaf. Kernel, meal and a little flour — the braai table’s quiet bread.",
      it:"Pane di granturco dolce. Chicchi, farina di mais, poca farina di grano.",
      sv:"Sötmajs i bröd. Kärnor, majsmjöl och lite vetemjöl."},
   i:{en:"300 g corn kernels (fresh or thawed), 100 g cornmeal, 80 g wholemeal flour, 2 tsp baking powder, ½ tsp salt, 2 eggs, 80 ml milk, 2 tbsp olive oil, 1 tbsp honey.",
      it:"300 g chicchi di mais, 100 g farina di mais, 80 g farina integrale, 2 cucchiaini lievito, ½ cucchiaino sale, 2 uova, 80 ml latte, 2 cucchiai olio, 1 cucchiaio miele.",
      sv:"300 g majskärnor, 100 g majsmjöl, 80 g fullkornsmjöl, 2 tsk bakpulver, ½ tsk salt, 2 ägg, 80 ml mjölk, 2 msk olja, 1 msk honung."},
   p:{en:"Heat oven to 180 °C. Blitz half the corn with eggs, milk, oil and honey. Stir in remaining corn, meals, baking powder and salt. Pour into an oiled loaf tin. Bake 35–40 minutes.",
      it:"Forno 180 °C. Frulla metà mais con uova, latte, olio, miele. Unisci il resto. Stampo. 35–40 minuti.",
      sv:"Ugn 180 °C. Mixa hälften av majsen med ägg, mjölk, olja, honung. Rör i resten. Form. 35–40 min."}},

  {id:"chapati",s:"ASIA",c:{en:"India",it:"India",sv:"Indien"},k:"flatbread",time:40,
   t:{en:"Chapati",it:"Chapati",sv:"Chapati"},
   w:{en:"Whole-wheat atta, water, a smear of ghee if you wish. The daily bread of millions, cooked on a dry pan.",
      it:"Atta integrale e acqua. Il pane quotidiano di milioni, in padella asciutta.",
      sv:"Fullkornsatta och vatten. Vardagsbröd för miljoner, i torr panna."},
   i:{en:"250 g atta or wholemeal flour, ½ tsp salt, 150–160 ml warm water, 1 tsp oil in the dough. Optional ghee for brushing.",
      it:"250 g atta o integrale, ½ cucchiaino sale, 150–160 ml acqua tiepida, 1 cucchiaino olio. Ghee a piacere.",
      sv:"250 g atta eller fullkornsmjöl, ½ tsk salt, 150–160 ml ljummet vatten, 1 tsk olja. Ghee om du vill."},
   p:{en:"Knead 5 minutes to a soft dough. Rest 20 minutes. Divide into 8. Roll thin discs. Cook on a hot dry tava or pan 30–40 seconds a side; press the edges and they should puff. Keep in a cloth.",
      it:"5 minuti, riposo 20. 8 dischi sottili. Padella rovente, 30–40 secondi per lato; gonfiano. Panno.",
      sv:"Knåda 5 min, vila 20. 8 tunna diskar. Het torr panna, 30–40 sek per sida. Puffar. Förvara i duk."}},

  {id:"mantou",s:"ASIA",c:{en:"China",it:"Cina",sv:"Kina"},k:"steamed",time:90,
   t:{en:"Mantou",it:"Mantou",sv:"Mantou"},
   w:{en:"Plain steamed buns. No oil in the dough if you skip it; the steam keeps them tender. Breakfast from Beijing to Sichuan.",
      it:"Panini al vapore, quasi senza grassi. La colazione da Pechino al Sichuan.",
      sv:"Ångade bullar utan stekning. Frukost från Peking till Sichuan."},
   i:{en:"300 g plain flour, 4 g instant yeast, 1 tbsp honey or sugar, ½ tsp salt, 160 ml warm water.",
      it:"300 g farina, 4 g lievito, 1 cucchiaio miele, ½ cucchiaino sale, 160 ml acqua tiepida.",
      sv:"300 g vetemjöl, 4 g jäst, 1 msk honung, ½ tsk salt, 160 ml ljummet vatten."},
   p:{en:"Knead smooth. Rise 1 hour. Divide into 8, shape tight balls or folds. Rest 20 minutes on parchment squares. Steam over boiling water 15 minutes. Rest 2 minutes with the lid ajar before lifting.",
      it:"1 ora. 8 palline, 20 min su carta. Vapore 15 minuti. 2 minuti col coperchio semiaperto.",
      sv:"Jäs 1 tim. 8 bullar, 20 min på papper. Ånga 15 min. Vila 2 min med gläntat lock."}},

  {id:"matcha-fin",s:"ASIA",c:{en:"Japan",it:"Giappone",sv:"Japan"},k:"cake",time:30,
   t:{en:"Matcha financiers",it:"Financier al matcha",sv:"Matchafinansier"},
   w:{en:"The French almond cake, given Japanese tea. Almonds and egg white, a little oil, no butter brown.",
      it:"Il financier francese col tè. Mandorle e albumi, poco olio.",
      sv:"Fransk mandelkaka med te. Mandel och äggvita, lite olja."},
   i:{en:"80 g ground almonds, 40 g flour, 60 g sugar, 1 tbsp matcha, pinch of salt, 3 egg whites, 40 ml mild olive oil or melted butter, ½ tsp vanilla.",
      it:"80 g mandorle, 40 g farina, 60 g zucchero, 1 cucchiaio matcha, sale, 3 albumi, 40 ml olio delicato, vaniglia.",
      sv:"80 g mandel, 40 g mjöl, 60 g socker, 1 msk matcha, salt, 3 äggvitor, 40 ml mild olja, vanilj."},
   p:{en:"Heat oven to 180 °C. Whisk whites until foamy, not stiff. Fold in dry ingredients, then oil. Spoon into a greased muffin tin (8 holes). Bake 12–14 minutes until the tops spring back.",
      it:"Forno 180 °C. Albumi schiumosi. Incorpora polveri e olio. 8 stampini. 12–14 minuti.",
      sv:"Ugn 180 °C. Fradgiga vitor. Vänd i pulver och olja. 8 formar. 12–14 min."}},

  {id:"banh-chuoi",s:"ASIA",c:{en:"Vietnam",it:"Vietnam",sv:"Vietnam"},k:"cake",time:55,
   t:{en:"Bánh chuối nướng",it:"Bánh chuối nướng",sv:"Bánh chuối nướng"},
   w:{en:"Baked banana custard cake. Ripe fruit, coconut milk, a little tapioca. Street dessert without a deep fryer.",
      it:"Torta-crema di banane al forno. Cocco e un poco di tapioca.",
      sv:"Bakad banankaka. Mogen frukt, kokosmjölk, lite tapioka."},
   i:{en:"4 very ripe bananas, 200 ml coconut milk, 2 eggs, 2 tbsp honey, 2 tbsp tapioca starch or cornflour, pinch of salt, 1 tsp vanilla, 1 tbsp toasted sesame or coconut flakes.",
      it:"4 banane matura, 200 ml latte di cocco, 2 uova, 2 cucchiai miele, 2 cucchiai fecola, sale, vaniglia, sesamo o cocco tostato.",
      sv:"4 mycket mogna bananer, 200 ml kokosmjölk, 2 ägg, 2 msk honung, 2 msk stärkelse, salt, vanilj, sesam eller kokos."},
   p:{en:"Heat oven to 180 °C. Mash 3 bananas; slice the fourth. Whisk mash with coconut milk, eggs, honey, starch, salt and vanilla. Pour into an oiled 20 cm dish, lay slices on top, sesame. Bake 35–40 minutes until set.",
      it:"Forno 180 °C. Schiaccia 3 banane, la quarta a fette. Mescola, versare, fette e sesamo. 35–40 minuti.",
      sv:"Ugn 180 °C. Mosa 3 bananer, skiva den fjärde. Vispa, häll upp, skivor och sesam. 35–40 min."}},

  {id:"bibingka",s:"ASIA",c:{en:"Philippines",it:"Filippine",sv:"Filippinerna"},k:"cake",time:45,
   t:{en:"Bibingka",it:"Bibingka",sv:"Bibingka"},
   w:{en:"Rice and coconut cake from the Christmas novena. Banana leaf if you have one; a tin if you don’t.",
      it:"Torta di riso e cocco della novena di Natale. Foglia di banano, o una teglia.",
      sv:"Risktårta med kokos från julnovenan. Banansblad om du har, annars en form."},
   i:{en:"150 g rice flour, 50 g sugar, 1 tsp baking powder, pinch of salt, 200 ml coconut milk, 1 egg, 1 tbsp oil, optional sliced banana or grated fresh coconut.",
      it:"150 g farina di riso, 50 g zucchero, 1 cucchiaino lievito, sale, 200 ml latte di cocco, 1 uovo, 1 cucchiaio olio, banana o cocco fresco.",
      sv:"150 g rismjöl, 50 g socker, 1 tsk bakpulver, salt, 200 ml kokosmjölk, 1 ägg, 1 msk olja, banan eller färsk kokos."},
   p:{en:"Heat oven to 190 °C. Whisk a batter. Line a 20 cm tin with a banana leaf or paper. Pour, add banana if using. Bake 25–30 minutes. Brush with a little coconut milk while hot.",
      it:"Forno 190 °C. Teglia 20 cm. 25–30 minuti. Spennella latte di cocco da calda.",
      sv:"Ugn 190 °C. Form 20 cm. 25–30 min. Pensla kokosmjölk medan den är het."}},

  {id:"anzac",s:"ASIA",c:{en:"Australia & Aotearoa",it:"Australia e Aotearoa",sv:"Australien & Aotearoa"},k:"cookie",time:30,
   t:{en:"Anzac biscuits",it:"Biscotti Anzac",sv:"Anzac-kakor"},
   w:{en:"Oats, coconut and golden syrup. Baked to travel to soldiers; still a honest biscuit. We keep the sugar modest.",
      it:"Avena, cocco, golden syrup. Nati per viaggiare lontano. Qui lo zucchero è misurato.",
      sv:"Havre, kokos och ljus sirap. Bakades för att tåla resan. Måttligt socker."},
   i:{en:"90 g rolled oats, 75 g wholemeal flour, 40 g desiccated coconut, 50 g brown sugar, pinch of salt, 60 g butter or 50 ml oil, 1 tbsp golden syrup or honey, ½ tsp bicarbonate of soda, 1 tbsp boiling water.",
      it:"90 g fiocchi d’avena, 75 g farina integrale, 40 g cocco, 50 g zucchero di canna, sale, 60 g burro o 50 ml olio, 1 cucchiaio miele, ½ cucchiaino bicarbonato, 1 cucchiaio acqua bollente.",
      sv:"90 g havregryn, 75 g fullkornsmjöl, 40 g kokos, 50 g farinsocker, salt, 60 g smör eller 50 ml olja, 1 msk honung, ½ tsk bikarbonat, 1 msk kokande vatten."},
   p:{en:"Heat oven to 170 °C. Mix dry ingredients. Melt fat with syrup. Stir soda into the boiling water, add to the fat — it foams. Mix into the oats. Flatten spoonfuls on a tray. Bake 12–15 minutes until amber.",
      it:"Forno 170 °C. Fondero grasso e miele, bicarbonato nell’acqua. Unisci. Cucchiaiate schiacciate. 12–15 minuti.",
      sv:"Ugn 170 °C. Smält fett och honung. Bikarbonat i vattnet, det fräser. Rör i gryn. Klickar. 12–15 min."}},

  {id:"arepas",s:"AMERICAS",c:{en:"Venezuela / Colombia",it:"Venezuela / Colombia",sv:"Venezuela / Colombia"},k:"flatbread",time:30,
   t:{en:"Arepas",it:"Arepas",sv:"Arepas"},
   w:{en:"Precooked corn masa and water. No wheat, no sugar. Split and fill with avocado, black beans, cheese.",
      it:"Masa precotta e acqua. Niente grano, niente zucchero. Apri e farcisci.",
      sv:"Förkokt majsamasa och vatten. Inget vete, inget socker. Dela och fyll."},
   i:{en:"200 g masarepa (pre-cooked white or yellow cornmeal), ½ tsp salt, 250 ml warm water, 1 tsp oil.",
      it:"200 g masarepa, ½ cucchiaino sale, 250 ml acqua tiepida, 1 cucchiaino olio.",
      sv:"200 g masarepa, ½ tsk salt, 250 ml ljummet vatten, 1 tsk olja."},
   p:{en:"Mix to a soft dough, rest 5 minutes. Divide into 6, shape discs 1.5 cm thick. Cook on a lightly oiled pan 6–7 minutes a side until a skin forms, then 10 minutes in a 180 °C oven to cook through. Split like a pita.",
      it:"Impasto morbido, 5 min. 6 dischi da 1,5 cm. Padella 6–7 min per lato, poi 10 min a 180 °C. Apri.",
      sv:"Mjuk deg, 5 min. 6 diskar 1,5 cm. Panna 6–7 min per sida, sedan 10 min i 180 °C. Dela."}},

  {id:"pao-queijo",s:"AMERICAS",c:{en:"Brazil",it:"Brasile",sv:"Brasilien"},k:"bread",time:35,
   t:{en:"Pão de queijo",it:"Pão de queijo",sv:"Pão de queijo"},
   w:{en:"Cassava starch puffs from Minas Gerais. Naturally gluten-free. Cheese is the flavour, not a blanket of fat.",
      it:"Palline di tapioca del Minas. Senza glutine. Il formaggio è il sapore.",
      sv:"Maniokpuffar från Minas. Naturligt glutenfria. Osten är smaken."},
   i:{en:"250 g tapioca starch (polvilho), 120 ml milk, 40 ml oil, 1 tsp salt, 1 egg, 80 g grated cheese (canastra, pecorino or mature cheddar).",
      it:"250 g fecola di tapioca, 120 ml latte, 40 ml olio, 1 cucchiaino sale, 1 uovo, 80 g formaggio grattugiato saporito.",
      sv:"250 g tapiokastärkelse, 120 ml mjölk, 40 ml olja, 1 tsk salt, 1 ägg, 80 g riven smakrik ost."},
   p:{en:"Heat oven to 200 °C. Bring milk, oil and salt to a simmer. Pour over the starch and beat. When lukewarm, beat in egg and cheese. Roll walnut balls. Bake 18–22 minutes until puffed and cracked.",
      it:"Forno 200 °C. Latte, olio e sale a sbollore sulla fecola. Tiepido: uovo e formaggio. Noci. 18–22 minuti.",
      sv:"Ugn 200 °C. Koka mjölk, olja, salt. Häll över stärkelsen. Ljummen: ägg och ost. Bollar. 18–22 min."}},

  {id:"pan-elote",s:"AMERICAS",c:{en:"Mexico",it:"Messico",sv:"Mexiko"},k:"cake",time:55,
   t:{en:"Pan de elote",it:"Pan de elote",sv:"Pan de elote"},
   w:{en:"Sweetcorn cake, closer to a pudding than a sponge. Corn is the sugar.",
      it:"Torta di granturco, quasi un budino. Il mais è lo zucchero.",
      sv:"Majskaka, mer pudding än sockerkaka. Majsen är sötman."},
   i:{en:"400 g sweetcorn kernels, 2 eggs, 80 g rice flour or plain flour, 40 g sugar, 1 tsp baking powder, pinch of salt, 80 ml milk, 2 tbsp oil, ½ tsp cinnamon.",
      it:"400 g mais dolce, 2 uova, 80 g farina di riso o 00, 40 g zucchero, 1 cucchiaino lievito, sale, 80 ml latte, 2 cucchiai olio, ½ cucchiaino cannella.",
      sv:"400 g sötmajs, 2 ägg, 80 g ris- eller vetemjöl, 40 g socker, 1 tsk bakpulver, salt, 80 ml mjölk, 2 msk olja, ½ tsk kanel."},
   p:{en:"Heat oven to 180 °C. Blend corn, eggs, milk and oil almost smooth, leaving a few kernels. Stir in flour, sugar, baking powder, salt and cinnamon. Pour into an oiled 20 cm tin. Bake 35–40 minutes.",
      it:"Forno 180 °C. Frulla mais, uova, latte, olio. Unisci le polveri. Stampo 20 cm. 35–40 minuti.",
      sv:"Ugn 180 °C. Mixa majs, ägg, mjölk, olja. Rör i pulver. Form 20 cm. 35–40 min."}},

  {id:"anadama",s:"AMERICAS",c:{en:"New England, USA",it:"New England",sv:"New England"},k:"bread",time:160,
   t:{en:"Anadama bread",it:"Pane anadama",sv:"Anadamabröd"},
   w:{en:"Cornmeal and molasses loaf from the Massachusetts coast. One sweet spoon for a whole tin.",
      it:"Mais e melassa della costa del Massachusetts. Un cucchiaio di dolce per tutta la forma.",
      sv:"Majsmjöl och mörk sirap från Massachusetts. En sked sötma till hela formen."},
   i:{en:"80 g cornmeal, 250 ml boiling water, 30 g molasses or dark honey, 1 tsp salt, 20 ml oil, 7 g instant yeast, 300 g flour (100 g wholemeal).",
      it:"80 g farina di mais, 250 ml acqua bollente, 30 g melassa o miele scuro, 1 cucchiaino sale, 20 ml olio, 7 g lievito, 300 g farina (100 g integrale).",
      sv:"80 g majsmjöl, 250 ml kokande vatten, 30 g mörk sirap, 1 tsk salt, 20 ml olja, 7 g jäst, 300 g mjöl (100 g fullkorn)."},
   p:{en:"Pour boiling water over cornmeal, stir in molasses, salt and oil. Cool to lukewarm. Add yeast and flour. Knead 6 minutes. Rise 1 hour. Shape a loaf, prove 40 minutes. Bake at 190 °C 35–40 minutes.",
      it:"Acqua bollente sul mais, melassa, sale, olio. Tiepido: lievito e farina. 1 ora, filone, 40 min. 190 °C 35–40.",
      sv:"Kokande vatten på majsmjölet, sirap, salt, olja. Ljummen: jäst och mjöl. 1 tim, limpa, 40 min. 190 °C 35–40."}},

  {id:"damper",s:"ASIA",c:{en:"Australia",it:"Australia",sv:"Australien"},k:"bread",time:45,
   t:{en:"Damper",it:"Damper",sv:"Damper"},
   w:{en:"Camp bread of the bush: self-raising flour and water, originally in the coals. We add yogurt and seeds.",
      it:"Pane da campo: farina e acqua, un tempo sotto la cenere. Qui yogurt e semi.",
      sv:"Buskens lägerbröd: mjöl och vatten, förr i glöden. Här yoghurt och fröer."},
   i:{en:"300 g wholemeal self-raising flour (or 300 g wholemeal + 2 tsp baking powder), ½ tsp salt, 200 g plain yogurt, 2 tbsp mixed seeds.",
      it:"300 g farina integrale + 2 cucchiaini lievito, ½ cucchiaino sale, 200 g yogurt, 2 cucchiai semi misti.",
      sv:"300 g fullkornsmjöl + 2 tsk bakpulver, ½ tsk salt, 200 g yoghurt, 2 msk blandade fröer."},
   p:{en:"Heat oven to 200 °C. Mix flour and salt, stir in yogurt to a rough dough. Shape a round, cut a cross, press on seeds. Bake 30–35 minutes until hollow-sounding.",
      it:"Forno 200 °C. Impasto rustico. Pagnotta, croce, semi. 30–35 minuti.",
      sv:"Ugn 200 °C. Grov deg. Rund, kors, fröer. 30–35 min."}});
