var RECIPES = [
  {id:"soda-bread",s:"EUROPE",c:{en:"Ireland",it:"Irlanda",sv:"Irland"},k:"bread",time:50,
   t:{en:"Brown soda bread",it:"Pane soda integrale",sv:"Brunt sodabröd"},
   w:{en:"Wholemeal wheat, buttermilk and no yeast — everyday Irish loaf, ready in an hour.",
      it:"Farina integrale, latticello, niente lievito. Il pane di tutti i giorni in Irlanda.",
      sv:"Fullkornsvete, filmjölk, ingen jäst. Vardagsbröd på en timme."},
   i:{en:"250 g wholemeal wheat flour, 250 g plain flour, 1 tsp bicarbonate of soda, 1 tsp fine salt, 400 ml buttermilk (or milk + 1 tbsp lemon juice, rested 10 min). Optional: 1 tbsp seeds on top.",
      it:"250 g farina integrale, 250 g farina 00, 1 cucchiaino bicarbonato, 1 cucchiaino sale, 400 ml latticello (o latte + 1 cucchiaio limone). Semi sopra a piacere.",
      sv:"250 g fullkornsvetemjöl, 250 g vetemjöl, 1 tsk bikarbonat, 1 tsk salt, 400 ml filmjölk (eller mjölk + 1 msk citron). Fröer på toppen om du vill."},
   p:{en:"Heat the oven to 200 °C. Mix flours, soda and salt. Pour in the buttermilk and stir to a soft, shaggy dough — do not knead. Shape a round on a floured tray, cut a deep cross. Bake 35–40 minutes until the bottom sounds hollow. Cool before slicing.",
      it:"Forno 200 °C. Mescola farine, bicarbonato e sale. Versa il latticello, impasta appena. Forma una pagnotta, incidi una croce. 35–40 minuti. Suona vuoto sotto.",
      sv:"Ugn 200 °C. Blanda mjöl, bikarbonat och salt. Häll i filmjölk, rör till en lös deg — knåda inte. Forma en rund, skär ett djupt kors. 35–40 min. Ska låta ihåligt under."}},

  {id:"knackebrod",s:"EUROPE",c:{en:"Sweden",it:"Svezia",sv:"Sverige"},k:"flatbread",time:40,
   t:{en:"Knäckebröd",it:"Knäckebröd",sv:"Knäckebröd"},
   w:{en:"Rye crisp with seeds. Long shelf life, high fibre, the taste of a Nordic cupboard.",
      it:"Sfoglia di segale e semi. Si conserva a lungo, tanta fibra.",
      sv:"Rågknäcke med fröer. Håller länge, mycket fiber, smakar skafferi."},
   i:{en:"200 g whole rye flour, 50 g sunflower or pumpkin seeds, ½ tsp salt, 1 tsp honey, 150 ml warm water, 1 tbsp oil.",
      it:"200 g farina di segale integrale, 50 g semi di girasole o zucca, ½ cucchiaino sale, 1 cucchiaino miele, 150 ml acqua tiepida, 1 cucchiaio olio.",
      sv:"200 g fullkornsrågmjöl, 50 g solros- eller pumpafrön, ½ tsk salt, 1 tsk honung, 150 ml ljummet vatten, 1 msk olja."},
   p:{en:"Heat the oven to 200 °C. Mix everything to a firm dough. Divide in two. Roll each piece paper-thin between parchment. Prick all over, sprinkle a little salt. Bake 12–15 minutes until dry and golden at the edges. Cool on a rack; it crisps as it cools.",
      it:"Forno 200 °C. Impasto sodo. Due sfoglie sottilissime tra carta forno. Bucherella. 12–15 minuti, bordi dorati. Si croccola raffreddando.",
      sv:"Ugn 200 °C. Fast deg. Dela i två, kavla pappers tunt mellan bakplåtspapper. Nagga. 12–15 min tills kanten är gyllene. Frasigt när det svalnat."}},

  {id:"roggenbrot",s:"EUROPE",c:{en:"Germany",it:"Germania",sv:"Tyskland"},k:"bread",time:180,
   t:{en:"Simple rye loaf",it:"Pane di segale",sv:"Enkelt rågbröd"},
   w:{en:"A home version of Bauernbrot: rye, a little wheat, yogurt for a mild sourness. Dense, good with soup.",
      it:"Bauernbrot di casa: segale, un po’ di grano, yogurt per l’acidità. Compatto, per la zuppa.",
      sv:"Hemmasnickrat bondbröd: råg, lite vete, yoghurt för syra. Tätt, till soppa."},
   i:{en:"300 g whole rye flour, 200 g wholemeal wheat flour, 7 g instant yeast, 10 g salt, 1 tbsp molasses or dark honey, 150 g plain yogurt, 250 ml warm water, 1 tsp caraway (optional).",
      it:"300 g segale integrale, 200 g frumento integrale, 7 g lievito secco, 10 g sale, 1 cucchiaio melassa o miele scuro, 150 g yogurt, 250 ml acqua tiepida, 1 cucchiaino cumino dei prati.",
      sv:"300 g råg, 200 g fullkornsvete, 7 g torrjäst, 10 g salt, 1 msk mörk honung, 150 g yoghurt, 250 ml ljummet vatten, 1 tsk kummin."},
   p:{en:"Mix all ingredients to a sticky dough. Cover 1 hour. Oil a loaf tin, scrape the dough in, level with wet hands. Prove 45 minutes. Bake at 220 °C for 15 minutes, then 190 °C for 35–40 minutes. Cool completely before cutting.",
      it:"Impasto appiccicoso. Lievita 1 ora. Stampo oliato, livella con mani bagnate. Altre 45 min. 220 °C 15 min, poi 190 °C 35–40. Taglia freddo.",
      sv:"Klibbig deg. Jäs 1 tim. Oljad form, släta med blöta händer. Jäs 45 min. 220 °C 15 min, sedan 190 °C 35–40. Skär helt kall."}},

  {id:"yogurt-cake",s:"EUROPE",c:{en:"France",it:"Francia",sv:"Frankrike"},k:"cake",time:50,
   t:{en:"Gâteau au yaourt",it:"Torta allo yogurt",sv:"Yoghurtkaka"},
   w:{en:"The French child’s first cake: measured with the yogurt pot. Olive oil instead of butter keeps it light.",
      it:"La prima torta dei bambini francesi, misurata col vasetto. Olio al posto del burro.",
      sv:"Franska barns första kaka, måttad med yoghurtburken. Olivolja istället för smör."},
   i:{en:"1 pot (125 g) plain yogurt, 2 pots flour (half wholemeal if you like), 1 pot sugar, ½ pot extra-virgin olive oil, 2 eggs, 1 tsp baking powder, zest of 1 lemon, pinch of salt.",
      it:"1 vasetto (125 g) yogurt, 2 vasetti farina (anche metà integrale), 1 vasetto zucchero, ½ vasetto olio EVO, 2 uova, 1 cucchiaino lievito, scorza di limone, pizzico di sale.",
      sv:"1 burk (125 g) yoghurt, 2 burkar mjöl (gärna hälften fullkorn), 1 burk socker, ½ burk olivolja, 2 ägg, 1 tsk bakpulver, citronskal, nypa salt."},
   p:{en:"Heat the oven to 180 °C. Butter or oil a loaf or 20 cm tin. Empty the yogurt, then use the pot as a measure. Whisk yogurt, eggs, sugar, oil and zest. Fold in flour, baking powder and salt. Bake 35–40 minutes until a skewer comes out clean.",
      it:"Forno 180 °C. Stampo 20 cm. Sbatti yogurt, uova, zucchero, olio e scorza. Incorpora farina e lievito. 35–40 minuti.",
      sv:"Ugn 180 °C. Form 20 cm. Vispa yoghurt, ägg, socker, olja och skal. Vänd i mjöl och bakpulver. 35–40 min."}},

  {id:"oatcakes",s:"EUROPE",c:{en:"Scotland",it:"Scozia",sv:"Skottland"},k:"cookie",time:30,
   t:{en:"Oatcakes",it:"Oatcakes scozzesi",sv:"Havrekakor"},
   w:{en:"Almost only oats and a little fat. Eaten with cheese or honey in the Highlands for centuries.",
      it:"Quasi solo avena. Con formaggio o miele, da secoli sugli Highlands.",
      sv:"Nästan bara havre. Med ost eller honung på höglandet i århundraden."},
   i:{en:"200 g fine oatmeal (or blitzed rolled oats), ½ tsp salt, ½ tsp bicarbonate of soda, 30 g butter or olive oil, 75–90 ml hot water.",
      it:"200 g farina d’avena fine, ½ cucchiaino sale, ½ cucchiaino bicarbonato, 30 g burro o olio, 75–90 ml acqua calda.",
      sv:"200 g fin havregrynsmjöl, ½ tsk salt, ½ tsk bikarbonat, 30 g smör eller olja, 75–90 ml hett vatten."},
   p:{en:"Heat the oven to 190 °C. Mix dry ingredients. Rub in the fat. Add just enough hot water to bind. Roll 3 mm thick on oatmeal. Cut rounds. Bake 15–18 minutes until the edges colour. Cool on a rack.",
      it:"Forno 190 °C. Unisci il grasso alle polveri, acqua calda q.b. Stendi 3 mm, ritaglia. 15–18 minuti.",
      sv:"Ugn 190 °C. Nibba i fettet. Hett vatten tills det håller. Kavla 3 mm, skär runda. 15–18 min."}},

  {id:"szarlotka",s:"EUROPE",c:{en:"Poland",it:"Polonia",sv:"Polen"},k:"cake",time:70,
   t:{en:"Szarlotka",it:"Szarlotka",sv:"Szarlotka"},
   w:{en:"Polish apple cake: a short wholemeal crust and a thick layer of fruit. More apple than pastry.",
      it:"Torta di mele polacca: frolla integrale e tanta frutta. Più mela che pasta.",
      sv:"Polsk äppelkaka: mördeg på fullkorn och ett tjockt lager frukt."},
   i:{en:"200 g wholemeal flour, 80 g cold butter, 2 tbsp sugar, 1 egg, pinch of salt. Filling: 800 g tart apples, 1 tbsp sugar, 1 tsp cinnamon, juice of ½ lemon.",
      it:"200 g farina integrale, 80 g burro freddo, 2 cucchiai zucchero, 1 uovo, sale. Ripieno: 800 g mele acide, 1 cucchiaio zucchero, 1 cucchiaino cannella, succo di mezzo limone.",
      sv:"200 g fullkornsmjöl, 80 g kallt smör, 2 msk socker, 1 ägg, salt. Fyllning: 800 g syrliga äpplen, 1 msk socker, 1 tsk kanel, saft av ½ citron."},
   p:{en:"Rub butter into flour, sugar and salt; add the egg to a dough. Chill 20 minutes. Peel and slice the apples with lemon, sugar and cinnamon. Heat oven to 180 °C. Press two-thirds of the dough into a 22 cm tin. Pile on the apples. Grate or crumble the rest over the top. Bake 40–45 minutes.",
      it:"Frolla, frigo 20 min. Mele a fette. Due terzi di pasta in teglia 22 cm, mele, briciole sopra. 180 °C per 40–45 minuti.",
      sv:"Mördeg, kyl 20 min. Skiva äpplena. ⅔ deg i form 22 cm, äpplen, resten smulad över. 180 °C 40–45 min."}},

  {id:"focaccia",s:"MED",c:{en:"Liguria, Italy",it:"Liguria",sv:"Ligurien"},k:"bread",time:150,
   t:{en:"Focaccia al rosmarino",it:"Focaccia al rosmarino",sv:"Focaccia med rosmarin"},
   w:{en:"Olive oil is the fat. A long rest replaces hard kneading. Eat with tomatoes, not as a vehicle for more oil.",
      it:"L’olio è il grasso. Il riposo sostituisce la fatica. Con i pomodori, non per inzupparne ancora.",
      sv:"Olivolja är fettet. Lång vila ersätter knådning. Ät med tomat."},
   i:{en:"400 g bread flour (or 280 g white + 120 g wholemeal), 7 g instant yeast, 8 g salt, 1 tsp honey, 300 ml lukewarm water, 4 tbsp extra-virgin olive oil, rosemary, flaky salt.",
      it:"400 g farina di forza (o 280 + 120 integrale), 7 g lievito, 8 g sale, 1 cucchiaino miele, 300 ml acqua tiepida, 4 cucchiai EVO, rosmarino, sale in scaglie.",
      sv:"400 g vetemjöl (eller 280 + 120 fullkorn), 7 g jäst, 8 g salt, 1 tsk honung, 300 ml ljummet vatten, 4 msk olivolja, rosmarin, flingsalt."},
   p:{en:"Stir flour, yeast, salt, honey and water to a sticky dough. Add 2 tbsp oil. Cover 1 hour, fold once. Oil a tray, stretch the dough into it, rest 30 minutes. Dimple with wet fingers, drizzle remaining oil, rosemary and salt. Bake at 220 °C 18–22 minutes.",
      it:"Impasto molle, 2 cucchiai d’olio. 1 ora, una piega. In teglia, 30 min. Bucature, olio, rosmarino, sale. 220 °C 18–22 min.",
      sv:"Klibbig deg, 2 msk olja. 1 tim, en vikning. I plåt, 30 min. Tryck hål, olja, rosmarin, salt. 220 °C 18–22 min."}},

  {id:"castagnaccio",s:"MED",c:{en:"Tuscany, Italy",it:"Toscana",sv:"Toscana"},k:"cake",time:50,
   t:{en:"Castagnaccio",it:"Castagnaccio",sv:"Castagnaccio"},
   w:{en:"Chestnut flour, olive oil, raisins, pine nuts, rosemary. No eggs, no sugar, no wheat. A poor cake that tastes of the woods.",
      it:"Farina di castagne, olio, uvetta, pinoli, rosmarino. Senza uova, zucchero, grano.",
      sv:"Kastanjemjöl, olivolja, russin, pinjenötter, rosmarin. Inga ägg, inget socker, inget vete."},
   i:{en:"250 g chestnut flour, 400 ml water, 2 tbsp extra-virgin olive oil, 30 g raisins (soaked), 20 g pine nuts, 1 sprig rosemary, pinch of salt, 1 tbsp extra oil for the pan.",
      it:"250 g farina di castagne, 400 ml acqua, 2 cucchiai EVO, 30 g uvetta ammollata, 20 g pinoli, rosmarino, sale, 1 cucchiaio d’olio per la teglia.",
      sv:"250 g kastanjemjöl, 400 ml vatten, 2 msk olivolja, 30 g blötlagda russin, 20 g pinjenötter, rosmarin, salt, 1 msk olja till formen."},
   p:{en:"Heat the oven to 180 °C. Whisk chestnut flour, water, salt and 2 tbsp oil to a batter like heavy cream. Stir in raisins. Pour into an oiled 24 cm tin. Scatter pine nuts and rosemary, trickle a little oil. Bake 30–35 minutes until the surface cracks and the edges pull away.",
      it:"Forno 180 °C. Impasto fluido. Teglia 24 cm, pinoli e rosmarino. 30–35 minuti, superficie crepata.",
      sv:"Ugn 180 °C. Smet som tjock grädde. Form 24 cm, nötter och rosmarin. 30–35 min tills ytan spricker."}},

  {id:"socca",s:"MED",c:{en:"Nice / Liguria",it:"Nizza / Liguria",sv:"Nice / Ligurien"},k:"flatbread",time:40,
   t:{en:"Socca · farinata",it:"Socca · farinata",sv:"Socca · farinata"},
   w:{en:"Chickpea flour and olive oil. Street food of Nice and Genoa: protein, no gluten, four ingredients.",
      it:"Farina di ceci e olio. Cibo di strada a Nizza e Genova: proteine, senza glutine.",
      sv:"Kikärtsmjöl och olivolja. Gatumat i Nice och Genua: protein, utan gluten."},
   i:{en:"150 g chickpea flour, 300 ml water, ½ tsp salt, 2 tbsp extra-virgin olive oil, black pepper, optional rosemary.",
      it:"150 g farina di ceci, 300 ml acqua, ½ cucchiaino sale, 2 cucchiai EVO, pepe, rosmarino.",
      sv:"150 g kikärtsmjöl, 300 ml vatten, ½ tsk salt, 2 msk olivolja, peppar, rosmarin."},
   p:{en:"Whisk flour, water and salt. Rest 20 minutes. Heat the oven to 250 °C with a well-oiled 24 cm pan inside. Pour in the batter, remaining oil on top. Bake 12–15 minutes until blistered and brown at the edges. Pepper, cut in wedges, eat hot.",
      it:"Scola 20 min. Forno 250 °C, teglia rovente oliata. 12–15 minuti, bordi bruciacchiati. Pepe, cuneo, calda.",
      sv:"Vila 20 min. Ugn 250 °C, het oljad panna. 12–15 min, brända kanter. Peppar, ät het."}},

  {id:"portokali",s:"MED",c:{en:"Greece",it:"Grecia",sv:"Grekland"},k:"cake",time:55,
   t:{en:"Olive-oil orange cake",it:"Torta all’arancia e olio",sv:"Apelsinkaka med olivolja"},
   w:{en:"A Greek-style cake with yogurt and oil instead of butter. Whole orange zest, not syrup.",
      it:"Torta greca con yogurt e olio. Scorza d’arancia, niente bagna.",
      sv:"Grekisk kaka med yoghurt och olja. Apelsinskal, inte sockerlag."},
   i:{en:"180 g flour (half wholemeal), 80 g sugar, 2 tsp baking powder, pinch of salt, 2 eggs, 120 g Greek yogurt, 80 ml extra-virgin olive oil, zest of 2 oranges, 2 tbsp orange juice.",
      it:"180 g farina (metà integrale), 80 g zucchero, 2 cucchiaini lievito, sale, 2 uova, 120 g yogurt greco, 80 ml EVO, scorza di 2 arance, 2 cucchiai succo.",
      sv:"180 g mjöl (hälften fullkorn), 80 g socker, 2 tsk bakpulver, salt, 2 ägg, 120 g grekisk yoghurt, 80 ml olivolja, skal av 2 apelsiner, 2 msk juice."},
   p:{en:"Heat the oven to 175 °C. Oil a 20 cm tin. Whisk eggs, sugar, yogurt, oil, zest and juice. Fold in flour, baking powder and salt. Bake 35–40 minutes. Cool in the tin 10 minutes.",
      it:"Forno 175 °C, stampo 20 cm. Sbatti i liquidi, incorpora le polveri. 35–40 minuti.",
      sv:"Ugn 175 °C, form 20 cm. Vispa det våta, vänd i det torra. 35–40 min."}},

  {id:"tortas-aceite",s:"MED",c:{en:"Andalusia, Spain",it:"Andalusia",sv:"Andalusien"},k:"cookie",time:35,
   t:{en:"Tortas de aceite",it:"Tortas de aceite",sv:"Tortas de aceite"},
   w:{en:"Seville’s thin olive-oil biscuits. Anise and orange. Almost no sugar, shatteringly crisp.",
      it:"Sfoglie d’olio di Siviglia. Anice e arancia. Poco zucchero, fragilissime.",
      sv:"Sevillas tunna oljekakor. Anis och apelsin. Lite socker, spröda."},
   i:{en:"200 g plain flour, 60 ml extra-virgin olive oil, 60 ml warm water, 1 tbsp sugar, ½ tsp salt, ½ tsp aniseed or fennel, zest of ½ orange, sesame seeds.",
      it:"200 g farina, 60 ml EVO, 60 ml acqua tiepida, 1 cucchiaio zucchero, ½ cucchiaino sale, ½ cucchiaino anice o finocchio, scorza d’arancia, sesamo.",
      sv:"200 g vetemjöl, 60 ml olivolja, 60 ml ljummet vatten, 1 msk socker, ½ tsk salt, ½ tsk anis eller fänkål, apelsinskal, sesam."},
   p:{en:"Mix to a soft dough. Rest 15 minutes. Heat oven to 200 °C. Divide into 10 balls. Roll each very thin. Sprinkle sesame and a pinch of sugar. Bake 8–10 minutes until golden in spots.",
      it:"Impasto morbido, 15 min. 10 palline, stendi sottilissimo. Sesamo. 200 °C 8–10 minuti.",
      sv:"Mjuk deg, 15 min. 10 bollar, kavla mycket tunt. Sesam. 200 °C 8–10 min."}},

  {id:"manakish",s:"LEVANT",c:{en:"Lebanon",it:"Libano",sv:"Libanon"},k:"flatbread",time:90,
   t:{en:"Manakish za’atar",it:"Manakish al za’atar",sv:"Manakish med za’atar"},
   w:{en:"Breakfast of Beirut: a soft flatbread painted with thyme, sesame and olive oil.",
      it:"Colazione di Beirut: sfoglia morbida con timo, sesamo e olio.",
      sv:"Beiruts frukost: mjukt bröd med timjan, sesam och olivolja."},
   i:{en:"300 g flour (50 g wholemeal), 5 g instant yeast, 1 tsp salt, 1 tsp honey, 180 ml warm water, 1 tbsp olive oil. Topping: 3 tbsp za’atar mixed with 3 tbsp olive oil.",
      it:"300 g farina (50 g integrale), 5 g lievito, 1 cucchiaino sale, 1 cucchiaino miele, 180 ml acqua, 1 cucchiaio olio. Copertura: 3 cucchiai za’atar + 3 cucchiai olio.",
      sv:"300 g mjöl (50 g fullkorn), 5 g jäst, 1 tsk salt, 1 tsk honung, 180 ml vatten, 1 msk olja. Topping: 3 msk za’atar + 3 msk olja."},
   p:{en:"Knead a soft dough. Rise 1 hour. Heat oven to 230 °C. Divide in four, roll 5 mm thick. Dimple, spread za’atar oil. Bake 8–10 minutes until the edges blister. Eat with cucumber, tomato and labneh.",
      it:"Impasto morbido, 1 ora. Quattro dischi da 5 mm. Za’atar. 230 °C 8–10 minuti. Con cetriolo, pomodoro, labneh.",
      sv:"Mjuk deg, 1 tim. Fyra diskar 5 mm. Za’atar. 230 °C 8–10 min. Med gurka, tomat, labneh."}},

  {id:"pita",s:"LEVANT",c:{en:"Levant",it:"Levante",sv:"Levanten"},k:"flatbread",time:100,
   t:{en:"Pita",it:"Pita",sv:"Pita"},
   w:{en:"Pocket bread from a hot oven. Wholemeal keeps it honest. Fill with herbs, not only meat.",
      it:"Pane tasca dal forno molto caldo. Integrale. Ripieno di erbe, non solo carne.",
      sv:"Fickbröd ur het ugn. Fullkorn. Fyll med örter, inte bara kött."},
   i:{en:"300 g flour (100 g wholemeal), 5 g instant yeast, 1 tsp salt, 1 tsp honey, 190 ml warm water, 1 tbsp olive oil.",
      it:"300 g farina (100 g integrale), 5 g lievito, 1 cucchiaino sale, 1 cucchiaino miele, 190 ml acqua, 1 cucchiaio olio.",
      sv:"300 g mjöl (100 g fullkorn), 5 g jäst, 1 tsk salt, 1 tsk honung, 190 ml vatten, 1 msk olja."},
   p:{en:"Knead 8 minutes. Rise 1 hour. Divide into 6 balls, rest 15 minutes. Roll 5 mm discs. Bake on a preheated stone or tray at 250 °C for 3–4 minutes until they puff. Wrap in a cloth so they stay soft.",
      it:"8 minuti di impasto, 1 ora. 6 palline, 15 min. Dischi 5 mm. Pietra a 250 °C, 3–4 minuti. Panno per tenerle morbide.",
      sv:"Knåda 8 min, jäs 1 tim. 6 bollar, 15 min. 5 mm. 250 °C 3–4 min tills de puffar. Linda in i duk."}},

  {id:"sfouf",s:"LEVANT",c:{en:"Lebanon",it:"Libano",sv:"Libanon"},k:"cake",time:45,
   t:{en:"Sfouf",it:"Sfouf",sv:"Sfouf"},
   w:{en:"Turmeric-gold semolina cake. Olive oil, tahini in the tin, no butter. Almonds on top.",
      it:"Torta d’oro alla curcuma e semola. Olio, tahina nello stampo, mandorle.",
      sv:"Guldgul semolinakaka med gurkmeja. Olivolja, tahini i formen, mandel."},
   i:{en:"200 g fine semolina, 80 g flour, 80 g sugar, 2 tsp turmeric, 2 tsp baking powder, pinch of salt, 200 ml milk, 80 ml olive oil, 1 tsp tahini for the tin, handful of pine nuts or almonds.",
      it:"200 g semola fine, 80 g farina, 80 g zucchero, 2 cucchiaini curcuma, 2 cucchiaini lievito, sale, 200 ml latte, 80 ml olio, 1 cucchiaino tahina per lo stampo, pinoli o mandorle.",
      sv:"200 g fin semolina, 80 g mjöl, 80 g socker, 2 tsk gurkmeja, 2 tsk bakpulver, salt, 200 ml mjölk, 80 ml olivolja, 1 tsk tahini till formen, pinje eller mandel."},
   p:{en:"Heat the oven to 180 °C. Brush a 20 cm tin with tahini. Mix dry ingredients. Stir in milk and oil. Pour, scatter nuts. Bake 30–35 minutes. Cut in diamonds, as in Beirut.",
      it:"Forno 180 °C. Stampo con tahina. Unisci liquidi. Frutta secca. 30–35 minuti. Taglia a rombi.",
      sv:"Ugn 180 °C. Pensla formen med tahini. Rör i mjölk och olja. Nötter. 30–35 min. Skär i rutor."}},

  {id:"tahini-cookies",s:"LEVANT",c:{en:"Levant",it:"Levante",sv:"Levanten"},k:"cookie",time:30,
   t:{en:"Tahini cookies",it:"Biscotti al tahina",sv:"Tahinikakor"},
   w:{en:"Sesame paste, a little honey, whole wheat. The pantry biscuit of the eastern Mediterranean.",
      it:"Pasta di sesamo, poco miele, integrale. Il biscotto della dispensa levantina.",
      sv:"Sesampasta, lite honung, fullkorn. Skafferikakan vid östra Medelhavet."},
   i:{en:"120 g tahini, 60 g honey, 1 egg, 150 g wholemeal flour, ½ tsp baking powder, pinch of salt, sesame seeds to roll.",
      it:"120 g tahina, 60 g miele, 1 uovo, 150 g farina integrale, ½ cucchiaino lievito, sale, sesamo.",
      sv:"120 g tahini, 60 g honung, 1 ägg, 150 g fullkornsmjöl, ½ tsk bakpulver, salt, sesam."},
   p:{en:"Heat the oven to 175 °C. Stir tahini, honey and egg. Add flour, baking powder and salt. Roll walnut-sized balls in sesame. Flatten slightly. Bake 12–14 minutes; they firm as they cool.",
      it:"Forno 175 °C. Mescola, forma noci, passa nel sesamo. 12–14 minuti. Si assodano freddi.",
      sv:"Ugn 175 °C. Rör ihop, valnötstora bollar i sesam. 12–14 min. Stelnar när de svalnar."}}
];
